// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyImageToConfig(arg1:string):Promise<string>;

export function GetImageBase64(arg1:string):Promise<string>;

export function ListConfigImages():Promise<Array<string>>;

export function LoadConfig():Promise<main.Config>;

export function RunCommandAsync(arg1:string):Promise<void>;

export function RunCommandSync(arg1:string):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectImage():Promise<string>;
