// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyImageToConfig(arg1) {
  return window['go']['main']['App']['CopyImageToConfig'](arg1);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RunCommandAsync(arg1) {
  return window['go']['main']['App']['RunCommandAsync'](arg1);
}

export function RunCommandSync(arg1) {
  return window['go']['main']['App']['RunCommandSync'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}
